#!/bin/bash
# This shell script builds the api docs for msiempy 
# I've been running it from MacOS but I beleive it's valid on Linux too. 

# Will first write the docs under the version's folder, and then overwrites default (lastest in the root folder). 
# See the mkdocs site under ./site folder or 2nd CLI argument

# Requirements: graphviz, pydoctor mkdocs mkdocs-awesome-pages-plugin
# sudo apt-get install graphviz || sudo yum install graphviz || brew install graphviz

# Stop if errors
set -euo pipefail

function restore_docs_folder()
{
    # Restore docs folder
    if [[ -d ./docs-tmp ]]; then
        rm -rf ./docs
        cp -r ./docs-tmp ./docs
        rm -rf ./docs-tmp
    fi
}

trap restore_docs_folder EXIT

# The out folder  
site=${1:-"./site"}

mkdir -p "${site}"

# Install python requirements
python3 setup.py install
python3 -m pip install -r requirements.txt
python3 -m pip install pydoctor mkdocs mkdocs-awesome-pages-plugin

# Figure the project version
project_version="$(python3 -c 'from msiempy import VERSION; print(VERSION)')"

# This folder must exists i.e. docs/0.3.5/
docs_site_version="./docs/${project_version}"
mkdir -p "${docs_site_version}"

# Figure commit ref
git_sha="$(git rev-parse HEAD)"
if ! git describe --exact-match --tags; then
    tag="Warning: Not a tagged version."
else
    git_sha="$(git describe --exact-match --tags)"
    tag="Tag: ${git_sha}."
fi


# Insert an auto ganerated index

echo "# msiempy ${project_version}

<!-- The mkdocs index to should show msiempy version in the header -->

*This is an autogenerated index for msiempy version ${project_version}, git reference [${git_sha}](https://github.com/mfesiem/msiempy/tree/${git_sha})*.  
*${tag}*  
*Generated from branch ${branch}, on the $(date).  

**[View documentation](msiempy.html)**

- A listing of [all modules and packages](moduleIndex.html), organized by package hierarchy.
- A listing of [all classes](classIndex.html), organized by inheritance hierarchy.
- A listing of [all functions, classes, modules and packages](nameIndex.html), ordered by name.

(built by [pydoctor](https://github.com/twisted/pydoctor))

[Github | README](https://github.com/mfesiem/msiempy) 
    
" > "${docs_site_version}/index.md"

# Backup docs folder
if [[ -d ./docs ]]; then
    cp -r docs docs-tmp
fi


# Generate diagrams under the ./docs/version folder

pyreverse -s 1 -f PUB_ONLY -o png -m y msiempy
mv ./classes.png "${docs_site_version}"
mv ./packages.png "${docs_site_version}"


# Run pydoctor build, just before the mkdocs build
# The index.html will be overwritten

pydoctor \
    --add-package=msiempy \
    --project-name="msiempy" \
    --html-viewsource-base="https://github.com/mfesiem/msiempy/tree/${git_sha}" \
    --make-html \
    --project-base-dir="$(pwd)" \
    --docformat=restructuredtext \
    --intersphinx=https://docs.python.org/3/objects.inv \
    --html-output="${docs_site_version}"

# Copy the docs in the versionned folder to the latest (root folder)
cp -rf ${docs_site_version}/* "./docs"

# Run mkdocs build, overwrite pydoctor index.html files
mkdocs build --site-dir "${site}"

restore_docs_folder