#!/bin/bash
# This shell script builds the docs for msiempy 
# I've been running it from MacOS but I beleive it's valid on Linux too. 

# It will automatically generate pydoctor documentation coupled with mkdocs to show different versions
# It also adds git reference and tag info

# Will first write the docs under the version's folder, and then overwrites default (lastest in the root folder). 
# See the mkdocs site under ./site folder 
# Then it will copy the content to your storage location: The 1rt CLI argument. Or  ./multi_version_site by default
# The storage should not be deleted and you should use the same storage for all versions. ./site will still contain the genrated site

# Requirements: graphviz, pydoctor mkdocs mkdocs-awesome-pages-plugin
# sudo apt-get install graphviz || sudo yum install graphviz || brew install graphviz

# Usage ./build_docs "./mfesiem.github.io/docs/test/msiempy"

# Stop if errors
set -euo pipefail

function restore_docs_folder()
{
    # Restore docs folder
    if [[ -d ./docs-tmp ]]; then
        rm -rf ./docs
        cp -r ./docs-tmp ./docs
        rm -rf ./docs-tmp
    fi
}

trap restore_docs_folder EXIT

# The out folder # This should be sychronized with alternative storage.  
multi_version_site=${1:-"./multi_version_site"}
mkdir -p "${multi_version_site}"

# Install python requirements
python3 setup.py install
python3 -m pip install -r requirements.txt
python3 -m pip install pydoctor mkdocs mkdocs-awesome-pages-plugin

# Figure the project version
project_version="$(python3 setup.py -V)"

# This folder must exists i.e. docs/0.3.5/
docs_site_version="./docs/${project_version}"
mkdir -p "${docs_site_version}"

# Generate diagrams under the ./docs/version folder

pyreverse -s 1 -f PUB_ONLY -o png -m y msiempy
mv ./classes.png "${docs_site_version}"
mv ./packages.png "${docs_site_version}"

# Figure commit ref
git_sha="$(git rev-parse HEAD)"
if ! git describe --exact-match --tags; then
    tag="Warning: Not a tagged version."
else
    git_sha="$(git describe --exact-match --tags)"
    tag="Tag: ${git_sha}."
fi

#Figure out branch
branch=$(git rev-parse --abbrev-ref HEAD)

# Include readme
readme=$(cat ./README.md)

# Autogenerated index
echo "# msiempy ${project_version}

<!-- The mkdocs index to should show msiempy version in the header -->

*This is an autogenerated index for [msiempy](https://github.com/mfesiem/msiempy/) version ${project_version}, git reference [${git_sha}](https://github.com/mfesiem/msiempy/tree/${git_sha})*.  
*${tag}*  
*Generated from branch ${branch}, on the $(date).*    

# API Docs

**[View the documentation summary](msiempy.html)** 

Or go directly to one of the following object documentation:

-   [ESM](msiempy.ESM.html)
-   [DataSource](msiempy.DataSource.html)
-   [DevTree](msiempy.DevTree.html)
-   [Alarm](msiempy.Alarm.html)
-   [AlarmManager](msiempy.AlarmManager.html)
-   [Event](msiempy.Event.html)
-   [EventManager](msiempy.EventManager.html)
-   [GroupedEventManager](msiempy.GroupedEventManager.html)
-   [Watchlist](msiempy.Watchlist.html)
-   [WatchlistManager](msiempy.WatchlistManager.html)
-   [NitroSession](msiempy.NitroSession.html)

Or navigate: 

- A listing of [all modules and packages](moduleIndex.html), organized by package hierarchy.
- A listing of [all classes](classIndex.html), organized by inheritance hierarchy.
- A listing of [all functions, classes, modules and packages](nameIndex.html), ordered by name.

Generated by [pydoctor](https://github.com/twisted/pydoctor). 

***

(bellow the readme)

${readme}
" > "${docs_site_version}/index.md"

# Backup docs folder right after creating index.md. Only index.md should be kept here
if [[ -d ./docs ]]; then
    cp -r docs docs-tmp
fi

# Generate diagrams under the ./docs/version folder

pyreverse -s 1 -f PUB_ONLY -o png -m y msiempy
mv ./classes.png "${docs_site_version}"
mv ./packages.png "${docs_site_version}"

# Generate 
python3 ./samples/list_request_args.py > "./all_request_args.rst"

# Run pydoctor build, just before the mkdocs build
# The index.html will be overwritten

pydoctor \
    --add-package=msiempy \
    --project-name="msiempy" \
    --html-viewsource-base="https://github.com/mfesiem/msiempy/tree/${git_sha}" \
    --make-html \
    --project-base-dir="$(pwd)" \
    --docformat=restructuredtext \
    --intersphinx=https://docs.python.org/3/objects.inv \
    --html-output="${docs_site_version}"

# Copy the docs in the versionned folder to the latest (root folder)
cp -rf ${docs_site_version}/* "./docs"

# Run mkdocs build, overwrite pydoctor index.html files
mkdocs build

# Copy the docs in the versionned folder to the site with multiples versions
cp -r ./site/* "${multi_version_site}"

restore_docs_folder