site_name: msiempy Documentation Index
site_description: msiempy Documentation Index
repo_url: https://github.com/mfesiem/msiempy
repo_name: GitHub
plugins:
  - search
  - awesome-pages:
        collapse_single_pages: true
nav:
    - "Latest": "index.md"
    - "Versions": 
        - ...
theme:
    name: mkdocs
    nav_style: dark
    custom_dir: _mkdocs_theme # Custom theme to remove the next/previous links in the header