name: publish
on: 
  push:
    branches: 
      - master
jobs: 
  deploy:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }} 

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
      max-parallel: 1
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
        with:
            # Fetches entire history, so we can analyze commits since last tag
            fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          apt-get install graphviz
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install .
          python -m pip show msiempy

      - name: Setup msiempy config
        run: python ./samples/msiempy_setup.py --set esm host ${{ secrets.esmhost }} --set esm user NGCP --set esm passwd ${{ secrets.esmpass }} --set general timeout 60
      
      - name: Run tests
        run: pytest --cov=./ --cov-report=xml --reruns 1 --reruns-delay 1
      
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: msiempy-code-coverage
          yml: ./codecov.yml 
          fail_ci_if_error: true

      - name: Generate documentation
        run: |
          python3 -m pdoc msiempy --output-dir docs_tmp --html --force --template-dir ./.pdoc_templates
          
          git clone https://github.com/mfesiem/mfesiem.github.io
          rm -rf ./mfesiem.github.io/docs/msiempy
          cp -r ./docs_tmp/msiempy mfesiem.github.io/docs/

          # pyreverse -s 1 -f PUB_ONLY -o png -m y msiempy
          # mv ./classes.png ./mfesiem.github.io/docs/msiempy
          # mv ./packages.png ./mfesiem.github.io/docs/msiempy

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.MFESIEM_GITHUB_IO_PRIVATE_KEY }}
          external_repository: mfesiem/mfesiem.github.io
          publish_dir: mfesiem.github.io
          publish_branch: 'master'
          user_name: 'Github Actions'
          user_email: "actions@github.com"
          commit_message: "Generate documentation - master"

      - name: Build msiempy
        run: python3 setup.py --quiet build check sdist bdist_wheel

      - name: Publish msiempy to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
      
      - name: Tag version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          version="$(python setup.py --version)"
          last_tag="$(git --no-pager tag -l | tail -1)"
          echo "msiempy ${version}" > ./tmp_tag.txt
          git --no-pager log ${last_tag}.. --pretty=oneline >> ./tmp_tag.txt
          git config --global user.email "actions@github.com"
          git config --global user.name "Github actions"
          git tag -a ${version} -F ./tmp_tag.txt
          git push --tags
