name: publish-test-docs-only
on: 
  push:
    branches: 
      - develop
jobs: 
  deploy:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }} 

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
      # max-parallel: 1
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install .
          python -m pip show msiempy

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MFESIEM_GITHUB_IO_PRIVATE_KEY }}
          known_hosts: github.com

      - name: Generate and Publish documentation
        run: |
          python3 -m pdoc msiempy --output-dir docs_tmp --html --force --template-dir ./.pdoc_templates
          
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          
          git clone https://github.com/mfesiem/mfesiem.github.io
          rm -rf ./mfesiem.github.io/docs/test/msiempy
          cp -r ./docs_tmp/msiempy mfesiem.github.io/docs/test/

          # pyreverse -s 1 -f PUB_ONLY -o png -m y msiempy
          # mv ./classes.png ./mfesiem.github.io/docs/test/msiempy
          # mv ./packages.png ./mfesiem.github.io/docs/test/msiempy

          cd ./mfesiem.github.io
          git add .
          git commit -m "Generated mfesiem.github.io/docs/test/msiempy"
          git push
          cd ..

      