name: test-and-publish-docs-dev
on: 
  push:
    branches: 
      - '*'
jobs: 
  test-and-publish-docs-dev:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }} 

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
      max-parallel: 1
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag
          fetch-depth: 0
          
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install .
          python -m pip show msiempy

      - name: Generate list of NitroSession.request() arguments to include in docstring
        run: |
          python ./samples/list_request_args.py > ./all_request_args.rst

      - name: Generate test documentation
        run: |

          git clone https://github.com/mfesiem/mfesiem.github.io
          rm -rf ./mfesiem.github.io/docs/test/msiempy
          mkdir ./mfesiem.github.io/docs/test/msiempy

          pydoctor \
           --add-package=msiempy \
            --project-name="McAfee SIEM Python Library" \
            --html-viewsource-base=https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA \
            --make-html \
            --project-base-dir="$(pwd)" \
            --docformat=restructuredtext \
            --intersphinx=https://docs.python.org/3/objects.inv \
            --html-output=mfesiem.github.io/docs/test/msiempy/


      - name: Generate diagrams
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install graphviz
          pyreverse -s 1 -f PUB_ONLY -o png -m y msiempy
          mv ./classes.png ./mfesiem.github.io/docs/test/msiempy
          mv ./packages.png ./mfesiem.github.io/docs/test/msiempy

      - name: Publish documentation to mfesiem.github.io/docs/test/msiempy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.MFESIEM_GITHUB_IO_PRIVATE_KEY }}
          external_repository: mfesiem/mfesiem.github.io
          publish_dir: mfesiem.github.io
          publish_branch: 'master'
          user_name: 'Github Actions'
          user_email: "actions@github.com"
          commit_message: "Generate documentation - (under test folder)"
          enable_jekyll: true
      
      - name: Setup msiempy config
        run: python ./samples/msiempy_setup.py --set esm host ${{ secrets.esmhost }} --set esm user NGCP --set esm passwd ${{ secrets.esmpass }} --set general timeout 60
      
      - name: Run tests
        run: python -m pytest --cov=./ --cov-report=xml --reruns 5 --reruns-delay 1

      - name: Build msiempy
        run: python setup.py --quiet build check sdist bdist_wheel


      